services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        ENVIRONMENT: development
    image: yokakit-dev
    container_name: yokakit-dev
    user: "www-data:www-data"
    working_dir: /var/www/html
    environment:
      APACHE_LOG_DIR: /var/log/apache2
    depends_on:
      db:
        condition: service_healthy
      mqtt:
        condition: service_started
    command: ["/usr/local/bin/app-entrypoint.sh"]
    volumes:
      - .:/workspace  # Mount project root as workspace
      - ./app/laravel:/var/www/html
    ports:
      - 18081:80  # Use different port to avoid conflicts with main web-app
      - 6002:6001   # Reverb WebSocket port
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - yokakit
