name: Docker Registry Publish

on:
  workflow_dispatch:  # Manual execution
    inputs:
      environment:
        description: 'Environment to build'
        required: true
        default: 'production'
        type: choice
        options:
          - 'production'
          - 'development'
          - 'both'
  push:
    branches: [ main ]
    tags: [ 'v*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        environment:
          - production
          - development

    steps:
      - name: Check if should build this environment
        id: should-build
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "both" ]] || \
             [[ "${{ github.event.inputs.environment }}" == "${{ matrix.environment }}" ]] || \
             [[ -z "${{ github.event.inputs.environment }}" && "${{ matrix.environment }}" == "production" ]]; then
            echo "build=true" >> $GITHUB_OUTPUT
          else
            echo "build=false" >> $GITHUB_OUTPUT
          fi

      - name: Checkout repository
        if: steps.should-build.outputs.build == 'true'
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        if: steps.should-build.outputs.build == 'true'
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Log in to Container Registry
        if: steps.should-build.outputs.build == 'true'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        if: steps.should-build.outputs.build == 'true'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch,suffix=-${{ matrix.environment }}
            type=ref,event=tag,suffix=-${{ matrix.environment }}
            type=raw,value=latest-${{ matrix.environment }},enable={{is_default_branch}}

      - name: Build and push Docker image
        if: steps.should-build.outputs.build == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          target: ${{ matrix.environment }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.environment }}
          cache-to: type=gha,mode=max,scope=${{ matrix.environment }}
          build-args: |
            ENVIRONMENT=${{ matrix.environment }}
